#Codificación DCPM (José Rodrigo Ávila, Valentina Hernández y Valeria Tavera)

import tkinter
import numpy as np
import random
from tkinter import *
from typing import TextIO

#Funcion crear matrices
def CreacionMatrices():
    Matriz=np.array([
    [Posicion1.get(), Posicion2.get(), Posicion3.get(), Posicion4.get(), Posicion5.get(), Posicion6.get(), Posicion7.get(), Posicion8.get(), Posicion9.get(), Posicion10.get()],
    [Posicion11.get(), Posicion12.get(), Posicion13.get(), Posicion14.get(), Posicion15.get(), Posicion16.get(), Posicion17.get(), Posicion18.get(), Posicion19.get(), Posicion20.get()],
    [Posicion21.get(), Posicion22.get(), Posicion23.get(), Posicion24.get(), Posicion25.get(), Posicion26.get(), Posicion27.get(), Posicion28.get(), Posicion29.get(), Posicion30.get()],
    [Posicion31.get(), Posicion32.get(), Posicion33.get(), Posicion34.get(), Posicion35.get(), Posicion36.get(), Posicion37.get(), Posicion38.get(), Posicion39.get(), Posicion40.get()],
    [Posicion41.get(), Posicion42.get(), Posicion43.get(), Posicion44.get(), Posicion45.get(), Posicion46.get(), Posicion47.get(), Posicion48.get(), Posicion49.get(), Posicion50.get()],
    [Posicion51.get(), Posicion52.get(), Posicion53.get(), Posicion54.get(), Posicion55.get(), Posicion56.get(), Posicion57.get(), Posicion58.get(), Posicion59.get(), Posicion60.get()],
    [Posicion61.get(), Posicion62.get(), Posicion63.get(), Posicion64.get(), Posicion65.get(), Posicion66.get(), Posicion67.get(), Posicion68.get(), Posicion69.get(), Posicion70.get()],
    [Posicion71.get(), Posicion72.get(), Posicion73.get(), Posicion74.get(), Posicion75.get(), Posicion76.get(), Posicion77.get(), Posicion78.get(), Posicion79.get(), Posicion80.get()],
    [Posicion81.get(), Posicion82.get(), Posicion83.get(), Posicion84.get(), Posicion85.get(), Posicion86.get(), Posicion87.get(), Posicion88.get(), Posicion89.get(), Posicion90.get()],
    [Posicion91.get(), Posicion92.get(), Posicion93.get(), Posicion94.get(), Posicion95.get(), Posicion96.get(), Posicion97.get(), Posicion98.get(), Posicion99.get(), Posicion100.get()]],dtype=np.dtype('U100'))
    
    Matriz2=np.array([
    [Posicion1.get(), Posicion2.get(), Posicion3.get(), Posicion4.get(), Posicion5.get(), Posicion6.get(), Posicion7.get(), Posicion8.get(), Posicion9.get(), Posicion10.get()],
    [Posicion11.get(), Posicion12.get(), Posicion13.get(), Posicion14.get(), Posicion15.get(), Posicion16.get(), Posicion17.get(), Posicion18.get(), Posicion19.get(), Posicion20.get()],
    [Posicion21.get(), Posicion22.get(), Posicion23.get(), Posicion24.get(), Posicion25.get(), Posicion26.get(), Posicion27.get(), Posicion28.get(), Posicion29.get(), Posicion30.get()],
    [Posicion31.get(), Posicion32.get(), Posicion33.get(), Posicion34.get(), Posicion35.get(), Posicion36.get(), Posicion37.get(), Posicion38.get(), Posicion39.get(), Posicion40.get()],
    [Posicion41.get(), Posicion42.get(), Posicion43.get(), Posicion44.get(), Posicion45.get(), Posicion46.get(), Posicion47.get(), Posicion48.get(), Posicion49.get(), Posicion50.get()],
    [Posicion51.get(), Posicion52.get(), Posicion53.get(), Posicion54.get(), Posicion55.get(), Posicion56.get(), Posicion57.get(), Posicion58.get(), Posicion59.get(), Posicion60.get()],
    [Posicion61.get(), Posicion62.get(), Posicion63.get(), Posicion64.get(), Posicion65.get(), Posicion66.get(), Posicion67.get(), Posicion68.get(), Posicion69.get(), Posicion70.get()],
    [Posicion71.get(), Posicion72.get(), Posicion73.get(), Posicion74.get(), Posicion75.get(), Posicion76.get(), Posicion77.get(), Posicion78.get(), Posicion79.get(), Posicion80.get()],
    [Posicion81.get(), Posicion82.get(), Posicion83.get(), Posicion84.get(), Posicion85.get(), Posicion86.get(), Posicion87.get(), Posicion88.get(), Posicion89.get(), Posicion90.get()],
    [Posicion91.get(), Posicion92.get(), Posicion93.get(), Posicion94.get(), Posicion95.get(), Posicion96.get(), Posicion97.get(), Posicion98.get(), Posicion99.get(), Posicion100.get()]],dtype=np.dtype('U100'))

    Minimo=ValorMinimoRandom.get()
    Maximo=ValorMaximoRandom.get()
    MaximaDiferencia=Intervalo.get()
    validar=0
    i=0
    while i<=9:
        j=0
        while j<=9:   
            Val=random.randint(int(Minimo),int(Maximo))
            Matriz[i,j]=Val        
            if (i==0 and j==0):
                Matriz2[i,j]=Matriz[i,j]
            else:
                if(j!=0):
                    Actual=int(Matriz[i,j])
                    Anterior=int(Matriz[i,j-1])
                else:
                    Actual=int(Matriz[i,j])
                    Anterior=int(Matriz[i-1,9])
                Diferencia=int(Actual-Anterior)
                if(Diferencia*-1)>int(MaximaDiferencia):
                    validar=1
                elif(Diferencia)>int(MaximaDiferencia):
                    validar=1
                else:
                    validar=0
                while validar==1:
                    Val=random.randint(int(Minimo),int(Maximo))
                    Matriz[i,j]=Val
                    if (i==0 and j==0):
                        Matriz2[i,j]=Matriz[i,j]
                    else:
                        if(j!=0):
                            Actual=int(Matriz[i,j])
                            Anterior=int(Matriz[i,j-1])
                        else:
                            Actual=int(Matriz[i,j])
                            Anterior=int(Matriz[i-1,9])
                        Diferencia=int(Actual-Anterior)
                    if(Diferencia*-1)>int(MaximaDiferencia):
                        validar=1
                    elif(Diferencia)>int(MaximaDiferencia):
                        validar=1
                    else:
                        validar=0
                Matriz2[i,j]=Diferencia          
            j=j+1
        i=i+1
    
    lista1=[Matriz[0,0],Matriz[0,1],Matriz[0,2],Matriz[0,3],Matriz[0,4],Matriz[0,5],Matriz[0,6],Matriz[0,7],Matriz[0,8],Matriz[0,9]]        
    lista2=[Matriz[1,0],Matriz[1,1],Matriz[1,2],Matriz[1,3],Matriz[1,4],Matriz[1,5],Matriz[1,6],Matriz[1,7],Matriz[1,8],Matriz[1,9]]
    lista3=[Matriz[2,0],Matriz[2,1],Matriz[2,2],Matriz[2,3],Matriz[2,4],Matriz[2,5],Matriz[2,6],Matriz[2,7],Matriz[2,8],Matriz[2,9]]
    lista4=[Matriz[3,0],Matriz[3,1],Matriz[3,2],Matriz[3,3],Matriz[3,4],Matriz[3,5],Matriz[3,6],Matriz[3,7],Matriz[3,8],Matriz[3,9]]
    lista5=[Matriz[4,0],Matriz[4,1],Matriz[4,2],Matriz[4,3],Matriz[4,4],Matriz[4,5],Matriz[4,6],Matriz[4,7],Matriz[4,8],Matriz[4,9]]
    lista6=[Matriz[5,0],Matriz[5,1],Matriz[5,2],Matriz[5,3],Matriz[5,4],Matriz[5,5],Matriz[5,6],Matriz[5,7],Matriz[5,8],Matriz[5,9]]
    lista7=[Matriz[6,0],Matriz[6,1],Matriz[6,2],Matriz[6,3],Matriz[6,4],Matriz[6,5],Matriz[6,6],Matriz[6,7],Matriz[6,8],Matriz[6,9]]
    lista8=[Matriz[7,0],Matriz[7,1],Matriz[7,2],Matriz[7,3],Matriz[7,4],Matriz[7,5],Matriz[7,6],Matriz[7,7],Matriz[7,8],Matriz[7,9]]
    lista9=[Matriz[8,0],Matriz[8,1],Matriz[8,2],Matriz[8,3],Matriz[8,4],Matriz[8,5],Matriz[8,6],Matriz[8,7],Matriz[8,8],Matriz[8,9]]
    lista10=[Matriz[9,0],Matriz[9,1],Matriz[9,2],Matriz[9,3],Matriz[9,4],Matriz[9,5],Matriz[9,6],Matriz[9,7],Matriz[9,8],Matriz[9,9]]

    Dlista1=[Matriz2[0,0],Matriz2[0,1],Matriz2[0,2],Matriz2[0,3],Matriz2[0,4],Matriz2[0,5],Matriz2[0,6],Matriz2[0,7],Matriz2[0,8],Matriz2[0,9]]        
    Dlista2=[Matriz2[1,0],Matriz2[1,1],Matriz2[1,2],Matriz2[1,3],Matriz2[1,4],Matriz2[1,5],Matriz2[1,6],Matriz2[1,7],Matriz2[1,8],Matriz2[1,9]]
    Dlista3=[Matriz2[2,0],Matriz2[2,1],Matriz2[2,2],Matriz2[2,3],Matriz2[2,4],Matriz2[2,5],Matriz2[2,6],Matriz2[2,7],Matriz2[2,8],Matriz2[2,9]]
    Dlista4=[Matriz2[3,0],Matriz2[3,1],Matriz2[3,2],Matriz2[3,3],Matriz2[3,4],Matriz2[3,5],Matriz2[3,6],Matriz2[3,7],Matriz2[3,8],Matriz2[3,9]]
    Dlista5=[Matriz2[4,0],Matriz2[4,1],Matriz2[4,2],Matriz2[4,3],Matriz2[4,4],Matriz2[4,5],Matriz2[4,6],Matriz2[4,7],Matriz2[4,8],Matriz2[4,9]]
    Dlista6=[Matriz2[5,0],Matriz2[5,1],Matriz2[5,2],Matriz2[5,3],Matriz2[5,4],Matriz2[5,5],Matriz2[5,6],Matriz2[5,7],Matriz2[5,8],Matriz2[5,9]]
    Dlista7=[Matriz2[6,0],Matriz2[6,1],Matriz2[6,2],Matriz2[6,3],Matriz2[6,4],Matriz2[6,5],Matriz2[6,6],Matriz2[6,7],Matriz2[6,8],Matriz2[6,9]]
    Dlista8=[Matriz2[7,0],Matriz2[7,1],Matriz2[7,2],Matriz2[7,3],Matriz2[7,4],Matriz2[7,5],Matriz2[7,6],Matriz2[7,7],Matriz2[7,8],Matriz2[7,9]]
    Dlista9=[Matriz2[8,0],Matriz2[8,1],Matriz2[8,2],Matriz2[8,3],Matriz2[8,4],Matriz2[8,5],Matriz2[8,6],Matriz2[8,7],Matriz2[8,8],Matriz2[8,9]]
    Dlista10=[Matriz2[9,0],Matriz2[9,1],Matriz2[9,2],Matriz2[9,3],Matriz2[9,4],Matriz2[9,5],Matriz2[9,6],Matriz2[9,7],Matriz2[9,8],Matriz2[9,9]]

    #Textos Matriz Diferencias
    Dtexto1=str(Dlista1[0])
    DArregloPos1.delete(0,END)
    DArregloPos1.insert(0,Dtexto1)
    Dtexto2=str(Dlista1[1])
    DArregloPos2.delete(0,END)
    DArregloPos2.insert(0,Dtexto2)
    Dtexto3=str(Dlista1[2])
    DArregloPos3.delete(0,END)
    DArregloPos3.insert(0,Dtexto3)
    Dtexto4=str(Dlista1[3])
    DArregloPos4.delete(0,END)
    DArregloPos4.insert(0,Dtexto4)
    Dtexto5=str(Dlista1[4])
    DArregloPos5.delete(0,END)
    DArregloPos5.insert(0,Dtexto5)
    Dtexto6=str(Dlista1[5])
    DArregloPos6.delete(0,END)
    DArregloPos6.insert(0,Dtexto6)
    Dtexto7=str(Dlista1[6])
    DArregloPos7.delete(0,END)
    DArregloPos7.insert(0,Dtexto7)
    Dtexto8=str(Dlista1[7])
    DArregloPos8.delete(0,END)
    DArregloPos8.insert(0,Dtexto8)
    Dtexto9=str(Dlista1[8])
    DArregloPos9.delete(0,END)
    DArregloPos9.insert(0,Dtexto9)
    Dtexto10=str(Dlista1[9])
    DArregloPos10.delete(0,END)
    DArregloPos10.insert(0,Dtexto10)

    Dtexto11=str(Dlista2[0])
    DArregloPos11.delete(0,END)
    DArregloPos11.insert(0,Dtexto11)
    Dtexto12=str(Dlista2[1])
    DArregloPos12.delete(0,END)
    DArregloPos12.insert(0,Dtexto12)
    Dtexto13=str(Dlista2[2])
    DArregloPos13.delete(0,END)
    DArregloPos13.insert(0,Dtexto13)
    Dtexto14=str(Dlista2[3])
    DArregloPos14.delete(0,END)
    DArregloPos14.insert(0,Dtexto14)
    Dtexto15=str(Dlista2[4])
    DArregloPos15.delete(0,END)
    DArregloPos15.insert(0,Dtexto15)
    Dtexto16=str(Dlista2[5])
    DArregloPos16.delete(0,END)
    DArregloPos16.insert(0,Dtexto16)
    Dtexto17=str(Dlista2[6])
    DArregloPos17.delete(0,END)
    DArregloPos17.insert(0,Dtexto17)
    Dtexto18=str(Dlista2[7])
    DArregloPos18.delete(0,END)
    DArregloPos18.insert(0,Dtexto18)
    Dtexto19=str(Dlista2[8])
    DArregloPos19.delete(0,END)
    DArregloPos19.insert(0,Dtexto19)
    Dtexto20=str(Dlista2[9])
    DArregloPos20.delete(0,END)
    DArregloPos20.insert(0,Dtexto20)

    Dtexto21=str(Dlista3[0])
    DArregloPos21.delete(0,END)
    DArregloPos21.insert(0,Dtexto21)
    Dtexto22=str(Dlista3[1])
    DArregloPos22.delete(0,END)
    DArregloPos22.insert(0,Dtexto22)
    Dtexto23=str(Dlista3[2])
    DArregloPos23.delete(0,END)
    DArregloPos23.insert(0,Dtexto23)
    Dtexto24=str(Dlista3[3])
    DArregloPos24.delete(0,END)
    DArregloPos24.insert(0,Dtexto24)
    Dtexto25=str(Dlista3[4])
    DArregloPos25.delete(0,END)
    DArregloPos25.insert(0,Dtexto25)
    Dtexto26=str(Dlista3[5])
    DArregloPos26.delete(0,END)
    DArregloPos26.insert(0,Dtexto26)
    Dtexto27=str(Dlista3[6])
    DArregloPos27.delete(0,END)
    DArregloPos27.insert(0,Dtexto27)
    Dtexto28=str(Dlista3[7])
    DArregloPos28.delete(0,END)
    DArregloPos28.insert(0,Dtexto28)
    Dtexto29=str(Dlista3[8])
    DArregloPos29.delete(0,END)
    DArregloPos29.insert(0,Dtexto29)
    Dtexto30=str(Dlista3[9])
    DArregloPos30.delete(0,END)
    DArregloPos30.insert(0,Dtexto30)

    Dtexto31=str(Dlista4[0])
    DArregloPos31.delete(0,END)
    DArregloPos31.insert(0,Dtexto31)
    Dtexto32=str(Dlista4[1])
    DArregloPos32.delete(0,END)
    DArregloPos32.insert(0,Dtexto32)
    Dtexto33=str(Dlista4[2])
    DArregloPos33.delete(0,END)
    DArregloPos33.insert(0,Dtexto33)
    Dtexto34=str(Dlista4[3])
    DArregloPos34.delete(0,END)
    DArregloPos34.insert(0,Dtexto34)
    Dtexto35=str(Dlista4[4])
    DArregloPos35.delete(0,END)
    DArregloPos35.insert(0,Dtexto35)
    Dtexto36=str(Dlista4[5])
    DArregloPos36.delete(0,END)
    DArregloPos36.insert(0,Dtexto36)
    Dtexto37=str(Dlista4[6])
    DArregloPos37.delete(0,END)
    DArregloPos37.insert(0,Dtexto37)
    Dtexto38=str(Dlista4[7])
    DArregloPos38.delete(0,END)
    DArregloPos38.insert(0,Dtexto38)
    Dtexto39=str(Dlista4[8])
    DArregloPos39.delete(0,END)
    DArregloPos39.insert(0,Dtexto39)
    Dtexto40=str(Dlista4[9])
    DArregloPos40.delete(0,END)
    DArregloPos40.insert(0,Dtexto40)

    Dtexto41=str(Dlista5[0])
    DArregloPos41.delete(0,END)
    DArregloPos41.insert(0,Dtexto41)
    Dtexto42=str(Dlista5[1])
    DArregloPos42.delete(0,END)
    DArregloPos42.insert(0,Dtexto42)
    Dtexto43=str(Dlista5[2])
    DArregloPos43.delete(0,END)
    DArregloPos43.insert(0,Dtexto43)
    Dtexto44=str(Dlista5[3])
    DArregloPos44.delete(0,END)
    DArregloPos44.insert(0,Dtexto44)
    Dtexto45=str(Dlista5[4])
    DArregloPos45.delete(0,END)
    DArregloPos45.insert(0,Dtexto45)
    Dtexto46=str(Dlista5[5])
    DArregloPos46.delete(0,END)
    DArregloPos46.insert(0,Dtexto46)
    Dtexto47=str(Dlista5[6])
    DArregloPos47.delete(0,END)
    DArregloPos47.insert(0,Dtexto47)
    Dtexto48=str(Dlista5[7])
    DArregloPos48.delete(0,END)
    DArregloPos48.insert(0,Dtexto48)
    Dtexto49=str(Dlista5[8])
    DArregloPos49.delete(0,END)
    DArregloPos49.insert(0,Dtexto49)
    Dtexto50=str(Dlista5[9])
    DArregloPos50.delete(0,END)
    DArregloPos50.insert(0,Dtexto50)

    Dtexto51=str(Dlista6[0])
    DArregloPos51.delete(0,END)
    DArregloPos51.insert(0,Dtexto51)
    Dtexto52=str(Dlista6[1])
    DArregloPos52.delete(0,END)
    DArregloPos52.insert(0,Dtexto52)
    Dtexto53=str(Dlista6[2])
    DArregloPos53.delete(0,END)
    DArregloPos53.insert(0,Dtexto53)
    Dtexto54=str(Dlista6[3])
    DArregloPos54.delete(0,END)
    DArregloPos54.insert(0,Dtexto54)
    Dtexto55=str(Dlista6[4])
    DArregloPos55.delete(0,END)
    DArregloPos55.insert(0,Dtexto55)
    Dtexto56=str(Dlista6[5])
    DArregloPos56.delete(0,END)
    DArregloPos56.insert(0,Dtexto56)
    Dtexto57=str(Dlista6[6])
    DArregloPos57.delete(0,END)
    DArregloPos57.insert(0,Dtexto57)
    Dtexto58=str(Dlista6[7])
    DArregloPos58.delete(0,END)
    DArregloPos58.insert(0,Dtexto58)
    Dtexto59=str(Dlista6[8])
    DArregloPos59.delete(0,END)
    DArregloPos59.insert(0,Dtexto59)
    Dtexto60=str(Dlista6[9])
    DArregloPos60.delete(0,END)
    DArregloPos60.insert(0,Dtexto60)

    Dtexto61=str(Dlista7[0])
    DArregloPos61.delete(0,END)
    DArregloPos61.insert(0,Dtexto61)
    Dtexto62=str(Dlista7[1])
    DArregloPos62.delete(0,END)
    DArregloPos62.insert(0,Dtexto62)
    Dtexto63=str(Dlista7[2])
    DArregloPos63.delete(0,END)
    DArregloPos63.insert(0,Dtexto63)
    Dtexto64=str(Dlista7[3])
    DArregloPos64.delete(0,END)
    DArregloPos64.insert(0,Dtexto64)
    Dtexto65=str(Dlista7[4])
    DArregloPos65.delete(0,END)
    DArregloPos65.insert(0,Dtexto65)
    Dtexto66=str(Dlista7[5])
    DArregloPos66.delete(0,END)
    DArregloPos66.insert(0,Dtexto66)
    Dtexto67=str(Dlista7[6])
    DArregloPos67.delete(0,END)
    DArregloPos67.insert(0,Dtexto67)
    Dtexto68=str(Dlista7[7])
    DArregloPos68.delete(0,END)
    DArregloPos68.insert(0,Dtexto68)
    Dtexto69=str(Dlista7[8])
    DArregloPos69.delete(0,END)
    DArregloPos69.insert(0,Dtexto69)
    Dtexto70=str(Dlista7[9])
    DArregloPos70.delete(0,END)
    DArregloPos70.insert(0,Dtexto70)

    Dtexto71=str(Dlista8[0])
    DArregloPos71.delete(0,END)
    DArregloPos71.insert(0,Dtexto71)
    Dtexto72=str(Dlista8[1])
    DArregloPos72.delete(0,END)
    DArregloPos72.insert(0,Dtexto72)
    Dtexto73=str(Dlista8[2])
    DArregloPos73.delete(0,END)
    DArregloPos73.insert(0,Dtexto73)
    Dtexto74=str(Dlista8[3])
    DArregloPos74.delete(0,END)
    DArregloPos74.insert(0,Dtexto74)
    Dtexto75=str(Dlista8[4])
    DArregloPos75.delete(0,END)
    DArregloPos75.insert(0,Dtexto75)
    Dtexto76=str(Dlista8[5])
    DArregloPos76.delete(0,END)
    DArregloPos76.insert(0,Dtexto76)
    Dtexto77=str(Dlista8[6])
    DArregloPos77.delete(0,END)
    DArregloPos77.insert(0,Dtexto77)
    Dtexto78=str(Dlista8[7])
    DArregloPos78.delete(0,END)
    DArregloPos78.insert(0,Dtexto78)
    Dtexto79=str(Dlista8[8])
    DArregloPos79.delete(0,END)
    DArregloPos79.insert(0,Dtexto79)
    Dtexto80=str(Dlista8[9])
    DArregloPos80.delete(0,END)
    DArregloPos80.insert(0,Dtexto80)

    Dtexto81=str(Dlista9[0])
    DArregloPos81.delete(0,END)
    DArregloPos81.insert(0,Dtexto81)
    Dtexto82=str(Dlista9[1])
    DArregloPos82.delete(0,END)
    DArregloPos82.insert(0,Dtexto82)
    Dtexto83=str(Dlista9[2])
    DArregloPos83.delete(0,END)
    DArregloPos83.insert(0,Dtexto83)
    Dtexto84=str(Dlista9[3])
    DArregloPos84.delete(0,END)
    DArregloPos84.insert(0,Dtexto84)
    Dtexto85=str(Dlista9[4])
    DArregloPos85.delete(0,END)
    DArregloPos85.insert(0,Dtexto85)
    Dtexto86=str(Dlista9[5])
    DArregloPos86.delete(0,END)
    DArregloPos86.insert(0,Dtexto86)
    Dtexto87=str(Dlista9[6])
    DArregloPos87.delete(0,END)
    DArregloPos87.insert(0,Dtexto87)
    Dtexto88=str(Dlista9[7])
    DArregloPos88.delete(0,END)
    DArregloPos88.insert(0,Dtexto88)
    Dtexto89=str(Dlista9[8])
    DArregloPos89.delete(0,END)
    DArregloPos89.insert(0,Dtexto89)
    Dtexto90=str(Dlista9[9])
    DArregloPos90.delete(0,END)
    DArregloPos90.insert(0,Dtexto90)

    Dtexto91=str(Dlista10[0])
    DArregloPos91.delete(0,END)
    DArregloPos91.insert(0,Dtexto91)
    Dtexto92=str(Dlista10[1])
    DArregloPos92.delete(0,END)
    DArregloPos92.insert(0,Dtexto92)
    Dtexto93=str(Dlista10[2])
    DArregloPos93.delete(0,END)
    DArregloPos93.insert(0,Dtexto93)
    Dtexto94=str(Dlista10[3])
    DArregloPos94.delete(0,END)
    DArregloPos94.insert(0,Dtexto94)
    Dtexto95=str(Dlista10[4])
    DArregloPos95.delete(0,END)
    DArregloPos95.insert(0,Dtexto95)
    Dtexto96=str(Dlista10[5])
    DArregloPos96.delete(0,END)
    DArregloPos96.insert(0,Dtexto96)
    Dtexto97=str(Dlista10[6])
    DArregloPos97.delete(0,END)
    DArregloPos97.insert(0,Dtexto97)
    Dtexto98=str(Dlista10[7])
    DArregloPos98.delete(0,END)
    DArregloPos98.insert(0,Dtexto98)
    Dtexto99=str(Dlista10[8])
    DArregloPos99.delete(0,END)
    DArregloPos99.insert(0,Dtexto99)
    Dtexto100=str(Dlista10[9])
    DArregloPos100.delete(0,END)
    DArregloPos100.insert(0,Dtexto100)

    #Textos Matriz Original
    texto1=str(lista1[0])
    ArregloPos1.delete(0,END)
    ArregloPos1.insert(0,texto1)
    texto2=str(lista1[1])
    ArregloPos2.delete(0,END)
    ArregloPos2.insert(0,texto2)
    texto3=str(lista1[2])
    ArregloPos3.delete(0,END)
    ArregloPos3.insert(0,texto3)
    texto4=str(lista1[3])
    ArregloPos4.delete(0,END)
    ArregloPos4.insert(0,texto4)
    texto5=str(lista1[4])
    ArregloPos5.delete(0,END)
    ArregloPos5.insert(0,texto5)
    texto6=str(lista1[5])
    ArregloPos6.delete(0,END)
    ArregloPos6.insert(0,texto6)
    texto7=str(lista1[6])
    ArregloPos7.delete(0,END)
    ArregloPos7.insert(0,texto7)
    texto8=str(lista1[7])
    ArregloPos8.delete(0,END)
    ArregloPos8.insert(0,texto8)
    texto9=str(lista1[8])
    ArregloPos9.delete(0,END)
    ArregloPos9.insert(0,texto9)
    texto10=str(lista1[9])
    ArregloPos10.delete(0,END)
    ArregloPos10.insert(0,texto10)

    texto11=str(lista2[0])
    ArregloPos11.delete(0,END)
    ArregloPos11.insert(0,texto11)
    texto12=str(lista2[1])
    ArregloPos12.delete(0,END)
    ArregloPos12.insert(0,texto12)
    texto13=str(lista2[2])
    ArregloPos13.delete(0,END)
    ArregloPos13.insert(0,texto13)
    texto14=str(lista2[3])
    ArregloPos14.delete(0,END)
    ArregloPos14.insert(0,texto14)
    texto15=str(lista2[4])
    ArregloPos15.delete(0,END)
    ArregloPos15.insert(0,texto15)
    texto16=str(lista2[5])
    ArregloPos16.delete(0,END)
    ArregloPos16.insert(0,texto16)
    texto17=str(lista2[6])
    ArregloPos17.delete(0,END)
    ArregloPos17.insert(0,texto17)
    texto18=str(lista2[7])
    ArregloPos18.delete(0,END)
    ArregloPos18.insert(0,texto18)
    texto19=str(lista2[8])
    ArregloPos19.delete(0,END)
    ArregloPos19.insert(0,texto19)
    texto20=str(lista2[9])
    ArregloPos20.delete(0,END)
    ArregloPos20.insert(0,texto20)

    texto21=str(lista3[0])
    ArregloPos21.delete(0,END)
    ArregloPos21.insert(0,texto21)
    texto22=str(lista3[1])
    ArregloPos22.delete(0,END)
    ArregloPos22.insert(0,texto22)
    texto23=str(lista3[2])
    ArregloPos23.delete(0,END)
    ArregloPos23.insert(0,texto23)
    texto24=str(lista3[3])
    ArregloPos24.delete(0,END)
    ArregloPos24.insert(0,texto24)
    texto25=str(lista3[4])
    ArregloPos25.delete(0,END)
    ArregloPos25.insert(0,texto25)
    texto26=str(lista3[5])
    ArregloPos26.delete(0,END)
    ArregloPos26.insert(0,texto26)
    texto27=str(lista3[6])
    ArregloPos27.delete(0,END)
    ArregloPos27.insert(0,texto27)
    texto28=str(lista3[7])
    ArregloPos28.delete(0,END)
    ArregloPos28.insert(0,texto28)
    texto29=str(lista3[8])
    ArregloPos29.delete(0,END)
    ArregloPos29.insert(0,texto29)
    texto30=str(lista3[9])
    ArregloPos30.delete(0,END)
    ArregloPos30.insert(0,texto30)

    texto31=str(lista4[0])
    ArregloPos31.delete(0,END)
    ArregloPos31.insert(0,texto31)
    texto32=str(lista4[1])
    ArregloPos32.delete(0,END)
    ArregloPos32.insert(0,texto32)
    texto33=str(lista4[2])
    ArregloPos33.delete(0,END)
    ArregloPos33.insert(0,texto33)
    texto34=str(lista4[3])
    ArregloPos34.delete(0,END)
    ArregloPos34.insert(0,texto34)
    texto35=str(lista4[4])
    ArregloPos35.delete(0,END)
    ArregloPos35.insert(0,texto35)
    texto36=str(lista4[5])
    ArregloPos36.delete(0,END)
    ArregloPos36.insert(0,texto36)
    texto37=str(lista4[6])
    ArregloPos37.delete(0,END)
    ArregloPos37.insert(0,texto37)
    texto38=str(lista4[7])
    ArregloPos38.delete(0,END)
    ArregloPos38.insert(0,texto38)
    texto39=str(lista4[8])
    ArregloPos39.delete(0,END)
    ArregloPos39.insert(0,texto39)
    texto40=str(lista4[9])
    ArregloPos40.delete(0,END)
    ArregloPos40.insert(0,texto40)

    texto41=str(lista5[0])
    ArregloPos41.delete(0,END)
    ArregloPos41.insert(0,texto41)
    texto42=str(lista5[1])
    ArregloPos42.delete(0,END)
    ArregloPos42.insert(0,texto42)
    texto43=str(lista5[2])
    ArregloPos43.delete(0,END)
    ArregloPos43.insert(0,texto43)
    texto44=str(lista5[3])
    ArregloPos44.delete(0,END)
    ArregloPos44.insert(0,texto44)
    texto45=str(lista5[4])
    ArregloPos45.delete(0,END)
    ArregloPos45.insert(0,texto45)
    texto46=str(lista5[5])
    ArregloPos46.delete(0,END)
    ArregloPos46.insert(0,texto46)
    texto47=str(lista5[6])
    ArregloPos47.delete(0,END)
    ArregloPos47.insert(0,texto47)
    texto48=str(lista5[7])
    ArregloPos48.delete(0,END)
    ArregloPos48.insert(0,texto48)
    texto49=str(lista5[8])
    ArregloPos49.delete(0,END)
    ArregloPos49.insert(0,texto49)
    texto50=str(lista5[9])
    ArregloPos50.delete(0,END)
    ArregloPos50.insert(0,texto50)

    texto51=str(lista6[0])
    ArregloPos51.delete(0,END)
    ArregloPos51.insert(0,texto51)
    texto52=str(lista6[1])
    ArregloPos52.delete(0,END)
    ArregloPos52.insert(0,texto52)
    texto53=str(lista6[2])
    ArregloPos53.delete(0,END)
    ArregloPos53.insert(0,texto53)
    texto54=str(lista6[3])
    ArregloPos54.delete(0,END)
    ArregloPos54.insert(0,texto54)
    texto55=str(lista6[4])
    ArregloPos55.delete(0,END)
    ArregloPos55.insert(0,texto55)
    texto56=str(lista6[5])
    ArregloPos56.delete(0,END)
    ArregloPos56.insert(0,texto56)
    texto57=str(lista6[6])
    ArregloPos57.delete(0,END)
    ArregloPos57.insert(0,texto57)
    texto58=str(lista6[7])
    ArregloPos58.delete(0,END)
    ArregloPos58.insert(0,texto58)
    texto59=str(lista6[8])
    ArregloPos59.delete(0,END)
    ArregloPos59.insert(0,texto59)
    texto60=str(lista6[9])
    ArregloPos60.delete(0,END)
    ArregloPos60.insert(0,texto60)

    texto61=str(lista7[0])
    ArregloPos61.delete(0,END)
    ArregloPos61.insert(0,texto61)
    texto62=str(lista7[1])
    ArregloPos62.delete(0,END)
    ArregloPos62.insert(0,texto62)
    texto63=str(lista7[2])
    ArregloPos63.delete(0,END)
    ArregloPos63.insert(0,texto63)
    texto64=str(lista7[3])
    ArregloPos64.delete(0,END)
    ArregloPos64.insert(0,texto64)
    texto65=str(lista7[4])
    ArregloPos65.delete(0,END)
    ArregloPos65.insert(0,texto65)
    texto66=str(lista7[5])
    ArregloPos66.delete(0,END)
    ArregloPos66.insert(0,texto66)
    texto67=str(lista7[6])
    ArregloPos67.delete(0,END)
    ArregloPos67.insert(0,texto67)
    texto68=str(lista7[7])
    ArregloPos68.delete(0,END)
    ArregloPos68.insert(0,texto68)
    texto69=str(lista7[8])
    ArregloPos69.delete(0,END)
    ArregloPos69.insert(0,texto69)
    texto70=str(lista7[9])
    ArregloPos70.delete(0,END)
    ArregloPos70.insert(0,texto70)

    texto71=str(lista8[0])
    ArregloPos71.delete(0,END)
    ArregloPos71.insert(0,texto71)
    texto72=str(lista8[1])
    ArregloPos72.delete(0,END)
    ArregloPos72.insert(0,texto72)
    texto73=str(lista8[2])
    ArregloPos73.delete(0,END)
    ArregloPos73.insert(0,texto73)
    texto74=str(lista8[3])
    ArregloPos74.delete(0,END)
    ArregloPos74.insert(0,texto74)
    texto75=str(lista8[4])
    ArregloPos75.delete(0,END)
    ArregloPos75.insert(0,texto75)
    texto76=str(lista8[5])
    ArregloPos76.delete(0,END)
    ArregloPos76.insert(0,texto76)
    texto77=str(lista8[6])
    ArregloPos77.delete(0,END)
    ArregloPos77.insert(0,texto77)
    texto78=str(lista8[7])
    ArregloPos78.delete(0,END)
    ArregloPos78.insert(0,texto78)
    texto79=str(lista8[8])
    ArregloPos79.delete(0,END)
    ArregloPos79.insert(0,texto79)
    texto80=str(lista8[9])
    ArregloPos80.delete(0,END)
    ArregloPos80.insert(0,texto80)

    texto81=str(lista9[0])
    ArregloPos81.delete(0,END)
    ArregloPos81.insert(0,texto81)
    texto82=str(lista9[1])
    ArregloPos82.delete(0,END)
    ArregloPos82.insert(0,texto82)
    texto83=str(lista9[2])
    ArregloPos83.delete(0,END)
    ArregloPos83.insert(0,texto83)
    texto84=str(lista9[3])
    ArregloPos84.delete(0,END)
    ArregloPos84.insert(0,texto84)
    texto85=str(lista9[4])
    ArregloPos85.delete(0,END)
    ArregloPos85.insert(0,texto85)
    texto86=str(lista9[5])
    ArregloPos86.delete(0,END)
    ArregloPos86.insert(0,texto86)
    texto87=str(lista9[6])
    ArregloPos87.delete(0,END)
    ArregloPos87.insert(0,texto87)
    texto88=str(lista9[7])
    ArregloPos88.delete(0,END)
    ArregloPos88.insert(0,texto88)
    texto89=str(lista9[8])
    ArregloPos89.delete(0,END)
    ArregloPos89.insert(0,texto89)
    texto90=str(lista9[9])
    ArregloPos90.delete(0,END)
    ArregloPos90.insert(0,texto90)

    texto91=str(lista10[0])
    ArregloPos91.delete(0,END)
    ArregloPos91.insert(0,texto91)
    texto92=str(lista10[1])
    ArregloPos92.delete(0,END)
    ArregloPos92.insert(0,texto92)
    texto93=str(lista10[2])
    ArregloPos93.delete(0,END)
    ArregloPos93.insert(0,texto93)
    texto94=str(lista10[3])
    ArregloPos94.delete(0,END)
    ArregloPos94.insert(0,texto94)
    texto95=str(lista10[4])
    ArregloPos95.delete(0,END)
    ArregloPos95.insert(0,texto95)
    texto96=str(lista10[5])
    ArregloPos96.delete(0,END)
    ArregloPos96.insert(0,texto96)
    texto97=str(lista10[6])
    ArregloPos97.delete(0,END)
    ArregloPos97.insert(0,texto97)
    texto98=str(lista10[7])
    ArregloPos98.delete(0,END)
    ArregloPos98.insert(0,texto98)
    texto99=str(lista10[8])
    ArregloPos99.delete(0,END)
    ArregloPos99.insert(0,texto99)
    texto100=str(lista10[9])
    ArregloPos100.delete(0,END)
    ArregloPos100.insert(0,texto100)
    
    return Matriz2

#Proceso Por Filas
def AgruparLecturaFilas(matriz):
    Valores=list()
    i=0
    while i < 10:
        j=0
        while j < 10:        
            valor=matriz[i,j]
            Valores.append(valor)                          
            j=j+1
        i=i+1

    ValoresMax=[int(val) for val in Valores]
    cont=0
    for i in ValoresMax:
        if i<0:
            ValoresMax[cont]=i*-1
        cont=cont+1

    MaximoVal = None
    for pos, num in enumerate(ValoresMax):
        if(MaximoVal is None or num > MaximoVal):
            MaximoVal=num

    BinarioVal=bin(int(MaximoVal))[2:]
    NumBits=(len(str(BinarioVal)))
    ResultadoBits=list()
    Valores=[int(val) for val in Valores]
    i=0
    while i<len(Valores):
        valorcito=ValoresMax[i]
        valorcito=bin(int(valorcito))[2:]
        if(len(str(valorcito))<NumBits):
            valorcito=str(valorcito).zfill(NumBits)  
        if(Valores[i]<0):
            valorcito="1"+valorcito
            ResultadoBits.append(valorcito)  
        elif(Valores[i]>=0):
            valorcito="0"+valorcito         
            ResultadoBits.append(valorcito)      
        i=i+1

    lista1=ResultadoBits[0:10]
    lista2=ResultadoBits[10:20]
    lista3=ResultadoBits[20:30]
    lista4=ResultadoBits[30:40]
    lista5=ResultadoBits[40:50]
    lista6=ResultadoBits[50:60]
    lista7=ResultadoBits[60:70]
    lista8=ResultadoBits[70:80]
    lista9=ResultadoBits[80:90]
    lista10=ResultadoBits[90:100]
    print(lista10)
    
    TextoLabelMostrarNumeroBits=("La cantidad de bits es de ",NumBits, " y el bit de signo")
    LabelMostrarNumeroBits.configure(text=TextoLabelMostrarNumeroBits)
    TextoLabelMostrarTramaTotal=("La trama resultante es: ",lista1,"\n",lista2,"\n",lista3,"\n",lista4,"\n",lista5,"\n",lista6,"\n",lista7,"\n",lista8,"\n",lista9,"\n",lista10)
    LabelMostrarTramaTotal.configure(text=TextoLabelMostrarTramaTotal)

#Proceso Por Columnas
def AgruparLecturaColumnas(matriz):
    Valores=list()
    i=0
    while i < 10:
        j=0
        while j < 10:        
            valor=matriz[j,i]
            Valores.append(valor)                          
            j=j+1
        i=i+1
   
    ValoresMax=[int(val) for val in Valores]
    cont=0
    for i in ValoresMax:
        if i<0:
            ValoresMax[cont]=i*-1
        cont=cont+1

    MaximoVal = None
    for pos, num in enumerate(ValoresMax):
        if(MaximoVal is None or num > MaximoVal):
            MaximoVal=num

    BinarioVal=bin(int(MaximoVal))[2:]
    NumBits=(len(str(BinarioVal)))
    ResultadoBits=list()
    i=0
    Valores=[int(val) for val in Valores]
    while i< len(Valores):
        valorcito=ValoresMax[i]
        valorcito=bin(int(valorcito))[2:]
        if(len(str(valorcito))<NumBits):
            valorcito=str(valorcito).zfill(NumBits)  
        if(Valores[i]<0):
            valorcito="1"+valorcito  
        elif(Valores[i]>=0):
            valorcito="0"+valorcito         
        ResultadoBits.append(valorcito)      
        i=i+1

    lista1=ResultadoBits[0:10]
    lista2=ResultadoBits[10:20]
    lista3=ResultadoBits[20:30]
    lista4=ResultadoBits[30:40]
    lista5=ResultadoBits[40:50]
    lista6=ResultadoBits[50:60]
    lista7=ResultadoBits[60:70]
    lista8=ResultadoBits[70:80]
    lista9=ResultadoBits[80:90]
    lista10=ResultadoBits[90:100]
    
    TextoLabelMostrarNumeroBits=("La cantidad de bits es de ",NumBits, " y el bit de signo")
    LabelMostrarNumeroBits.configure(text=TextoLabelMostrarNumeroBits)
    TextoLabelMostrarTramaTotal=("La trama resultante es: ",lista1,"\n",lista2,"\n",lista3,"\n",lista4,"\n",lista5,"\n",lista6,"\n",lista7,"\n",lista8,"\n",lista9,"\n",lista10)
    LabelMostrarTramaTotal.configure(text=TextoLabelMostrarTramaTotal)


#Proceso Por Zig Zag
def AgruparLecturaZigZag(matriz):
    alto=10
    ancho=10
    MatrizSolucion=[[] for i in range(ancho+alto-1)]

    for i in range(ancho):
        for j in range(alto):
            sum=i+j
            if(sum%2 ==0):
                MatrizSolucion[sum].insert(0,matriz[i][j])
            else:
                MatrizSolucion[sum].append(matriz[i][j])		
    Valores=list()
    for i in MatrizSolucion:
        for j in i:
                Valores.append(j)   
   
    ValoresMax=[int(val) for val in Valores]
    cont=0
    for i in ValoresMax:
        if i<0:
            ValoresMax[cont]=i*-1
        cont=cont+1

    MaximoVal = None
    for pos, num in enumerate(ValoresMax):
        if(MaximoVal is None or num > MaximoVal):
            MaximoVal=num

    BinarioVal=bin(int(MaximoVal))[2:]
    NumBits=(len(str(BinarioVal)))
    ResultadoBits=list()
    i=0
    Valores=[int(val) for val in Valores]
    while i< len(Valores):
        valorcito=ValoresMax[i]
        valorcito=bin(int(valorcito))[2:]
        if(len(str(valorcito))<NumBits):
            valorcito=str(valorcito).zfill(NumBits)  
        if(Valores[i]<0):
            valorcito="1"+valorcito  
        elif(Valores[i]>=0):
            valorcito="0"+valorcito         
        ResultadoBits.append(valorcito)      
        i=i+1

    lista1=ResultadoBits[0:10]
    lista2=ResultadoBits[10:20]
    lista3=ResultadoBits[20:30]
    lista4=ResultadoBits[30:40]
    lista5=ResultadoBits[40:50]
    lista6=ResultadoBits[50:60]
    lista7=ResultadoBits[60:70]
    lista8=ResultadoBits[70:80]
    lista9=ResultadoBits[80:90]
    lista10=ResultadoBits[90:100]
    
    TextoLabelMostrarNumeroBits=("La cantidad de bits es de ",NumBits, " y el bit de signo")
    LabelMostrarNumeroBits.configure(text=TextoLabelMostrarNumeroBits)
    TextoLabelMostrarTramaTotal=("La trama resultante es: ",lista1,"\n",lista2,"\n",lista3,"\n",lista4,"\n",lista5,"\n",lista6,"\n",lista7,"\n",lista8,"\n",lista9,"\n",lista10)
    LabelMostrarTramaTotal.configure(text=TextoLabelMostrarTramaTotal)

#Creación ventana
VentanaCodificacionDCPM=Tk()
VentanaCodificacionDCPM.title("Codificación DCPM")
VentanaCodificacionDCPM.geometry('1500x600')
TituloInterfaz=Label(VentanaCodificacionDCPM, text="Codificación DCPM", bd=10, fg='black', font=("Helvetica", 16))
TituloInterfaz.grid(row=0, column=0)

#Instrucciones
LabelInstrucciones=Label(VentanaCodificacionDCPM, text="ingrese la maxima diferencia para sus valores")
LabelInstrucciones.grid(row=1, column=0)
Espacio=Label(VentanaCodificacionDCPM,text="ingrese el valor minimo de los valores que desea")
Espacio.grid(row=3,column=0)
Intervalo=StringVar()
EntradaIntervalo=Entry(VentanaCodificacionDCPM,textvariable=Intervalo,width=20)
EntradaIntervalo.grid(row=2,column=0)

#Mostrar Matriz Inicial
#ValoresMatrizfila1
Posicion1=StringVar()
ArregloPos1=Entry(VentanaCodificacionDCPM,textvariable=Posicion1,width=5)
ArregloPos1.grid(row=3,column=2,sticky=NSEW)
Posicion2=StringVar()
ArregloPos2=Entry(VentanaCodificacionDCPM,textvariable=Posicion2,width=5)
ArregloPos2.grid(row=3,column=3,sticky=NSEW)
Posicion3=StringVar()
ArregloPos3=Entry(VentanaCodificacionDCPM,textvariable=Posicion3,width=5)
ArregloPos3.grid(row=3,column=4,sticky=NSEW)
Posicion4=StringVar()
ArregloPos4=Entry(VentanaCodificacionDCPM,textvariable=Posicion4,width=5)
ArregloPos4.grid(row=3,column=5,sticky=NSEW)
Posicion5=StringVar()
ArregloPos5=Entry(VentanaCodificacionDCPM,textvariable=Posicion5,width=5)
ArregloPos5.grid(row=3,column=6,sticky=NSEW)
Posicion6=StringVar()
ArregloPos6=Entry(VentanaCodificacionDCPM,textvariable=Posicion6,width=5)
ArregloPos6.grid(row=3,column=7,sticky=NSEW)
Posicion7=StringVar()
ArregloPos7=Entry(VentanaCodificacionDCPM,textvariable=Posicion7,width=5)
ArregloPos7.grid(row=3,column=8,sticky=NSEW)
Posicion8=StringVar()
ArregloPos8=Entry(VentanaCodificacionDCPM,textvariable=Posicion8,width=5)
ArregloPos8.grid(row=3,column=9,sticky=NSEW)
Posicion9=StringVar()
ArregloPos9=Entry(VentanaCodificacionDCPM,textvariable=Posicion9,width=5)
ArregloPos9.grid(row=3,column=10,sticky=NSEW)
Posicion10=StringVar()
ArregloPos10=Entry(VentanaCodificacionDCPM,textvariable=Posicion10,width=5)
ArregloPos10.grid(row=3,column=11,sticky=NSEW)

#ValoresMatrizFila2
Posicion11=StringVar()
ArregloPos11=Entry(VentanaCodificacionDCPM,textvariable=Posicion11,width=5)
ArregloPos11.grid(row=4,column=2,sticky=NSEW)
Posicion12=StringVar()
ArregloPos12=Entry(VentanaCodificacionDCPM,textvariable=Posicion12,width=5)
ArregloPos12.grid(row=4,column=3,sticky=NSEW)
Posicion13=StringVar()
ArregloPos13=Entry(VentanaCodificacionDCPM,textvariable=Posicion13,width=5)
ArregloPos13.grid(row=4,column=4,sticky=NSEW)
Posicion14=StringVar()
ArregloPos14=Entry(VentanaCodificacionDCPM,textvariable=Posicion14,width=5)
ArregloPos14.grid(row=4,column=5,sticky=NSEW)
Posicion15=StringVar()
ArregloPos15=Entry(VentanaCodificacionDCPM,textvariable=Posicion15,width=5)
ArregloPos15.grid(row=4,column=6,sticky=NSEW)
Posicion16=StringVar()
ArregloPos16=Entry(VentanaCodificacionDCPM,textvariable=Posicion16,width=5)
ArregloPos16.grid(row=4,column=7,sticky=NSEW)
Posicion17=StringVar()
ArregloPos17=Entry(VentanaCodificacionDCPM,textvariable=Posicion17,width=5)
ArregloPos17.grid(row=4,column=8,sticky=NSEW)
Posicion18=StringVar()
ArregloPos18=Entry(VentanaCodificacionDCPM,textvariable=Posicion18,width=5)
ArregloPos18.grid(row=4,column=9,sticky=NSEW)
Posicion19=StringVar()
ArregloPos19=Entry(VentanaCodificacionDCPM,textvariable=Posicion19,width=5)
ArregloPos19.grid(row=4,column=10,sticky=NSEW)
Posicion20=StringVar()
ArregloPos20=Entry(VentanaCodificacionDCPM,textvariable=Posicion20,width=5)
ArregloPos20.grid(row=4,column=11,sticky=NSEW)

#ValoresMatrizFila3
Posicion21=StringVar()
ArregloPos21=Entry(VentanaCodificacionDCPM,textvariable=Posicion21,width=5)
ArregloPos21.grid(row=5,column=2,sticky=NSEW)
Posicion22=StringVar()
ArregloPos22=Entry(VentanaCodificacionDCPM,textvariable=Posicion22,width=5)
ArregloPos22.grid(row=5,column=3,sticky=NSEW)
Posicion23=StringVar()
ArregloPos23=Entry(VentanaCodificacionDCPM,textvariable=Posicion23,width=5)
ArregloPos23.grid(row=5,column=4,sticky=NSEW)
Posicion24=StringVar()
ArregloPos24=Entry(VentanaCodificacionDCPM,textvariable=Posicion24,width=5)
ArregloPos24.grid(row=5,column=5,sticky=NSEW)
Posicion25=StringVar()
ArregloPos25=Entry(VentanaCodificacionDCPM,textvariable=Posicion25,width=5)
ArregloPos25.grid(row=5,column=6,sticky=NSEW)
Posicion26=StringVar()
ArregloPos26=Entry(VentanaCodificacionDCPM,textvariable=Posicion26,width=5)
ArregloPos26.grid(row=5,column=7,sticky=NSEW)
Posicion27=StringVar()
ArregloPos27=Entry(VentanaCodificacionDCPM,textvariable=Posicion27,width=5)
ArregloPos27.grid(row=5,column=8,sticky=NSEW)
Posicion28=StringVar()
ArregloPos28=Entry(VentanaCodificacionDCPM,textvariable=Posicion28,width=5)
ArregloPos28.grid(row=5,column=9,sticky=NSEW)
Posicion29=StringVar()
ArregloPos29=Entry(VentanaCodificacionDCPM,textvariable=Posicion29,width=5)
ArregloPos29.grid(row=5,column=10,sticky=NSEW)
Posicion30=StringVar()
ArregloPos30=Entry(VentanaCodificacionDCPM,textvariable=Posicion30,width=5)
ArregloPos30.grid(row=5,column=11,sticky=NSEW)

#ArregloMatrizFila4
Posicion31=StringVar()
ArregloPos31=Entry(VentanaCodificacionDCPM,textvariable=Posicion31,width=5)
ArregloPos31.grid(row=6,column=2,sticky=NSEW)
Posicion32=StringVar()
ArregloPos32=Entry(VentanaCodificacionDCPM,textvariable=Posicion32,width=5)
ArregloPos32.grid(row=6,column=3,sticky=NSEW)
Posicion33=StringVar()
ArregloPos33=Entry(VentanaCodificacionDCPM,textvariable=Posicion33,width=5)
ArregloPos33.grid(row=6,column=4,sticky=NSEW)
Posicion34=StringVar()
ArregloPos34=Entry(VentanaCodificacionDCPM,textvariable=Posicion34,width=5)
ArregloPos34.grid(row=6,column=5,sticky=NSEW)
Posicion35=StringVar()
ArregloPos35=Entry(VentanaCodificacionDCPM,textvariable=Posicion35,width=5)
ArregloPos35.grid(row=6,column=6,sticky=NSEW)
Posicion36=StringVar()
ArregloPos36=Entry(VentanaCodificacionDCPM,textvariable=Posicion36,width=5)
ArregloPos36.grid(row=6,column=7,sticky=NSEW)
Posicion37=StringVar()
ArregloPos37=Entry(VentanaCodificacionDCPM,textvariable=Posicion37,width=5)
ArregloPos37.grid(row=6,column=8,sticky=NSEW)
Posicion38=StringVar()
ArregloPos38=Entry(VentanaCodificacionDCPM,textvariable=Posicion38,width=5)
ArregloPos38.grid(row=6,column=9,sticky=NSEW)
Posicion39=StringVar()
ArregloPos39=Entry(VentanaCodificacionDCPM,textvariable=Posicion39,width=5)
ArregloPos39.grid(row=6,column=10,sticky=NSEW)
Posicion40=StringVar()
ArregloPos40=Entry(VentanaCodificacionDCPM,textvariable=Posicion40,width=5)
ArregloPos40.grid(row=6,column=11,sticky=NSEW)

#ArregloMatrizFila5
Posicion41=StringVar()
ArregloPos41=Entry(VentanaCodificacionDCPM,textvariable=Posicion41,width=5)
ArregloPos41.grid(row=7,column=2,sticky=NSEW)
Posicion42=StringVar()
ArregloPos42=Entry(VentanaCodificacionDCPM,textvariable=Posicion42,width=5)
ArregloPos42.grid(row=7,column=3,sticky=NSEW)
Posicion43=StringVar()
ArregloPos43=Entry(VentanaCodificacionDCPM,textvariable=Posicion43,width=5)
ArregloPos43.grid(row=7,column=4,sticky=NSEW)
Posicion44=StringVar()
ArregloPos44=Entry(VentanaCodificacionDCPM,textvariable=Posicion44,width=5)
ArregloPos44.grid(row=7,column=5,sticky=NSEW)
Posicion45=StringVar()
ArregloPos45=Entry(VentanaCodificacionDCPM,textvariable=Posicion45,width=5)
ArregloPos45.grid(row=7,column=6,sticky=NSEW)
Posicion46=StringVar()
ArregloPos46=Entry(VentanaCodificacionDCPM,textvariable=Posicion46,width=5)
ArregloPos46.grid(row=7,column=7,sticky=NSEW)
Posicion47=StringVar()
ArregloPos47=Entry(VentanaCodificacionDCPM,textvariable=Posicion47,width=5)
ArregloPos47.grid(row=7,column=8,sticky=NSEW)
Posicion48=StringVar()
ArregloPos48=Entry(VentanaCodificacionDCPM,textvariable=Posicion48,width=5)
ArregloPos48.grid(row=7,column=9,sticky=NSEW)
Posicion49=StringVar()
ArregloPos49=Entry(VentanaCodificacionDCPM,textvariable=Posicion49,width=5)
ArregloPos49.grid(row=7,column=10,sticky=NSEW)
Posicion50=StringVar()
ArregloPos50=Entry(VentanaCodificacionDCPM,textvariable=Posicion50,width=5)
ArregloPos50.grid(row=7,column=11,sticky=NSEW)

#ArregloMatrizFila6
Posicion51=StringVar()
ArregloPos51=Entry(VentanaCodificacionDCPM,textvariable=Posicion51,width=5)
ArregloPos51.grid(row=8,column=2,sticky=NSEW)
Posicion52=StringVar()
ArregloPos52=Entry(VentanaCodificacionDCPM,textvariable=Posicion52,width=5)
ArregloPos52.grid(row=8,column=3,sticky=NSEW)
Posicion53=StringVar()
ArregloPos53=Entry(VentanaCodificacionDCPM,textvariable=Posicion53,width=5)
ArregloPos53.grid(row=8,column=4,sticky=NSEW)
Posicion54=StringVar()
ArregloPos54=Entry(VentanaCodificacionDCPM,textvariable=Posicion54,width=5)
ArregloPos54.grid(row=8,column=5,sticky=NSEW)
Posicion55=StringVar()
ArregloPos55=Entry(VentanaCodificacionDCPM,textvariable=Posicion55,width=5)
ArregloPos55.grid(row=8,column=6,sticky=NSEW)
Posicion56=StringVar()
ArregloPos56=Entry(VentanaCodificacionDCPM,textvariable=Posicion56,width=5)
ArregloPos56.grid(row=8,column=7,sticky=NSEW)
Posicion57=StringVar()
ArregloPos57=Entry(VentanaCodificacionDCPM,textvariable=Posicion57,width=5)
ArregloPos57.grid(row=8,column=8,sticky=NSEW)
Posicion58=StringVar()
ArregloPos58=Entry(VentanaCodificacionDCPM,textvariable=Posicion58,width=5)
ArregloPos58.grid(row=8,column=9,sticky=NSEW)
Posicion59=StringVar()
ArregloPos59=Entry(VentanaCodificacionDCPM,textvariable=Posicion59,width=5)
ArregloPos59.grid(row=8,column=10,sticky=NSEW)
Posicion60=StringVar()
ArregloPos60=Entry(VentanaCodificacionDCPM,textvariable=Posicion60,width=5)
ArregloPos60.grid(row=8,column=11,sticky=NSEW)

#MatrizArregloFila7
Posicion61=StringVar()
ArregloPos61=Entry(VentanaCodificacionDCPM,textvariable=Posicion61,width=5)
ArregloPos61.grid(row=9,column=2,sticky=NSEW)
Posicion62=StringVar()
ArregloPos62=Entry(VentanaCodificacionDCPM,textvariable=Posicion62,width=5)
ArregloPos62.grid(row=9,column=3,sticky=NSEW)
Posicion63=StringVar()
ArregloPos63=Entry(VentanaCodificacionDCPM,textvariable=Posicion63,width=5)
ArregloPos63.grid(row=9,column=4,sticky=NSEW)
Posicion64=StringVar()
ArregloPos64=Entry(VentanaCodificacionDCPM,textvariable=Posicion64,width=5)
ArregloPos64.grid(row=9,column=5,sticky=NSEW)
Posicion65=StringVar()
ArregloPos65=Entry(VentanaCodificacionDCPM,textvariable=Posicion65,width=5)
ArregloPos65.grid(row=9,column=6,sticky=NSEW)
Posicion66=StringVar()
ArregloPos66=Entry(VentanaCodificacionDCPM,textvariable=Posicion66,width=5)
ArregloPos66.grid(row=9,column=7,sticky=NSEW)
Posicion67=StringVar()
ArregloPos67=Entry(VentanaCodificacionDCPM,textvariable=Posicion67,width=5)
ArregloPos67.grid(row=9,column=8,sticky=NSEW)
Posicion68=StringVar()
ArregloPos68=Entry(VentanaCodificacionDCPM,textvariable=Posicion68,width=5)
ArregloPos68.grid(row=9,column=9,sticky=NSEW)
Posicion69=StringVar()
ArregloPos69=Entry(VentanaCodificacionDCPM,textvariable=Posicion69,width=5)
ArregloPos69.grid(row=9,column=10,sticky=NSEW)
Posicion70=StringVar()
ArregloPos70=Entry(VentanaCodificacionDCPM,textvariable=Posicion70,width=5)
ArregloPos70.grid(row=9,column=11,sticky=NSEW)

#ArregloMatrizFila8
Posicion71=StringVar()
ArregloPos71=Entry(VentanaCodificacionDCPM,textvariable=Posicion71,width=5)
ArregloPos71.grid(row=10,column=2,sticky=NSEW)
Posicion72=StringVar()
ArregloPos72=Entry(VentanaCodificacionDCPM,textvariable=Posicion72,width=5)
ArregloPos72.grid(row=10,column=3,sticky=NSEW)
Posicion73=StringVar()
ArregloPos73=Entry(VentanaCodificacionDCPM,textvariable=Posicion73,width=5)
ArregloPos73.grid(row=10,column=4,sticky=NSEW)
Posicion74=StringVar()
ArregloPos74=Entry(VentanaCodificacionDCPM,textvariable=Posicion74,width=5)
ArregloPos74.grid(row=10,column=5,sticky=NSEW)
Posicion75=StringVar()
ArregloPos75=Entry(VentanaCodificacionDCPM,textvariable=Posicion75,width=5)
ArregloPos75.grid(row=10,column=6,sticky=NSEW)
Posicion76=StringVar()
ArregloPos76=Entry(VentanaCodificacionDCPM,textvariable=Posicion76,width=5)
ArregloPos76.grid(row=10,column=7,sticky=NSEW)
Posicion77=StringVar()
ArregloPos77=Entry(VentanaCodificacionDCPM,textvariable=Posicion77,width=5)
ArregloPos77.grid(row=10,column=8,sticky=NSEW)
Posicion78=StringVar()
ArregloPos78=Entry(VentanaCodificacionDCPM,textvariable=Posicion78,width=5)
ArregloPos78.grid(row=10,column=9,sticky=NSEW)
Posicion79=StringVar()
ArregloPos79=Entry(VentanaCodificacionDCPM,textvariable=Posicion79,width=5)
ArregloPos79.grid(row=10,column=10,sticky=NSEW)
Posicion80=StringVar()
ArregloPos80=Entry(VentanaCodificacionDCPM,textvariable=Posicion80,width=5)
ArregloPos80.grid(row=10,column=11,sticky=NSEW)

#ArregloMatrizFila9
Posicion81=StringVar()
ArregloPos81=Entry(VentanaCodificacionDCPM,textvariable=Posicion81,width=5)
ArregloPos81.grid(row=11,column=2,sticky=NSEW)
Posicion82=StringVar()
ArregloPos82=Entry(VentanaCodificacionDCPM,textvariable=Posicion82,width=5)
ArregloPos82.grid(row=11,column=3,sticky=NSEW)
Posicion83=StringVar()
ArregloPos83=Entry(VentanaCodificacionDCPM,textvariable=Posicion83,width=5)
ArregloPos83.grid(row=11,column=4,sticky=NSEW)
Posicion84=StringVar()
ArregloPos84=Entry(VentanaCodificacionDCPM,textvariable=Posicion84,width=5)
ArregloPos84.grid(row=11,column=5,sticky=NSEW)
Posicion85=StringVar()
ArregloPos85=Entry(VentanaCodificacionDCPM,textvariable=Posicion85,width=5)
ArregloPos85.grid(row=11,column=6,sticky=NSEW)
Posicion86=StringVar()
ArregloPos86=Entry(VentanaCodificacionDCPM,textvariable=Posicion86,width=5)
ArregloPos86.grid(row=11,column=7,sticky=NSEW)
Posicion87=StringVar()
ArregloPos87=Entry(VentanaCodificacionDCPM,textvariable=Posicion87,width=5)
ArregloPos87.grid(row=11,column=8,sticky=NSEW)
Posicion88=StringVar()
ArregloPos88=Entry(VentanaCodificacionDCPM,textvariable=Posicion88,width=5)
ArregloPos88.grid(row=11,column=9,sticky=NSEW)
Posicion89=StringVar()
ArregloPos89=Entry(VentanaCodificacionDCPM,textvariable=Posicion89,width=5)
ArregloPos89.grid(row=11,column=10,sticky=NSEW)
Posicion90=StringVar()
ArregloPos90=Entry(VentanaCodificacionDCPM,textvariable=Posicion90,width=5)
ArregloPos90.grid(row=11,column=11,sticky=NSEW)

#ArregloMatrizFila10
Posicion91=StringVar()
ArregloPos91=Entry(VentanaCodificacionDCPM,textvariable=Posicion91,width=5)
ArregloPos91.grid(row=12,column=2,sticky=NSEW)
Posicion92=StringVar()
ArregloPos92=Entry(VentanaCodificacionDCPM,textvariable=Posicion92,width=5)
ArregloPos92.grid(row=12,column=3,sticky=NSEW)
Posicion93=StringVar()
ArregloPos93=Entry(VentanaCodificacionDCPM,textvariable=Posicion93,width=5)
ArregloPos93.grid(row=12,column=4,sticky=NSEW)
Posicion94=StringVar()
ArregloPos94=Entry(VentanaCodificacionDCPM,textvariable=Posicion94,width=5)
ArregloPos94.grid(row=12,column=5,sticky=NSEW)
Posicion95=StringVar()
ArregloPos95=Entry(VentanaCodificacionDCPM,textvariable=Posicion95,width=5)
ArregloPos95.grid(row=12,column=6,sticky=NSEW)
Posicion96=StringVar()
ArregloPos96=Entry(VentanaCodificacionDCPM,textvariable=Posicion96,width=5) 
ArregloPos96.grid(row=12,column=7,sticky=NSEW)
Posicion97=StringVar()
ArregloPos97=Entry(VentanaCodificacionDCPM,textvariable=Posicion97,width=5)
ArregloPos97.grid(row=12,column=8,sticky=NSEW)
Posicion98=StringVar()
ArregloPos98=Entry(VentanaCodificacionDCPM,textvariable=Posicion98,width=5)
ArregloPos98.grid(row=12,column=9,sticky=NSEW)
Posicion99=StringVar()
ArregloPos99=Entry(VentanaCodificacionDCPM,textvariable=Posicion99,width=5)
ArregloPos99.grid(row=12,column=10,sticky=NSEW)
Posicion100=StringVar()
ArregloPos100=Entry(VentanaCodificacionDCPM,textvariable=Posicion100,width=5)
ArregloPos100.grid(row=12,column=11,sticky=NSEW)

#Mostrar Matriz Diferencia
#ValoresMatrizfila1
DPosicion1=StringVar()
DArregloPos1=Entry(VentanaCodificacionDCPM,textvariable=DPosicion1,width=5)
DArregloPos1.grid(row=14,column=2,sticky=NSEW)
DPosicion2=StringVar()
DArregloPos2=Entry(VentanaCodificacionDCPM,textvariable=DPosicion2,width=5)
DArregloPos2.grid(row=14,column=3,sticky=NSEW)
DPosicion3=StringVar()
DArregloPos3=Entry(VentanaCodificacionDCPM,textvariable=DPosicion3,width=5)
DArregloPos3.grid(row=14,column=4,sticky=NSEW)
DPosicion4=StringVar()
DArregloPos4=Entry(VentanaCodificacionDCPM,textvariable=DPosicion4,width=5)
DArregloPos4.grid(row=14,column=5,sticky=NSEW)
DPosicion5=StringVar()
DArregloPos5=Entry(VentanaCodificacionDCPM,textvariable=DPosicion5,width=5)
DArregloPos5.grid(row=14,column=6,sticky=NSEW)
DPosicion6=StringVar()
DArregloPos6=Entry(VentanaCodificacionDCPM,textvariable=DPosicion6,width=5)
DArregloPos6.grid(row=14,column=7,sticky=NSEW)
DPosicion7=StringVar()
DArregloPos7=Entry(VentanaCodificacionDCPM,textvariable=DPosicion7,width=5)
DArregloPos7.grid(row=14,column=8,sticky=NSEW)
DPosicion8=StringVar()
DArregloPos8=Entry(VentanaCodificacionDCPM,textvariable=DPosicion8,width=5)
DArregloPos8.grid(row=14,column=9,sticky=NSEW)
DPosicion9=StringVar()
DArregloPos9=Entry(VentanaCodificacionDCPM,textvariable=DPosicion9,width=5)
DArregloPos9.grid(row=14,column=10,sticky=NSEW)
DPosicion10=StringVar()
DArregloPos10=Entry(VentanaCodificacionDCPM,textvariable=DPosicion10,width=5)
DArregloPos10.grid(row=14,column=11,sticky=NSEW)

#ValoresMatrizFila2
DPosicion11=StringVar()
DArregloPos11=Entry(VentanaCodificacionDCPM,textvariable=DPosicion11,width=5)
DArregloPos11.grid(row=15,column=2,sticky=NSEW)
DPosicion12=StringVar()
DArregloPos12=Entry(VentanaCodificacionDCPM,textvariable=DPosicion12,width=5)
DArregloPos12.grid(row=15,column=3,sticky=NSEW)
DPosicion13=StringVar()
DArregloPos13=Entry(VentanaCodificacionDCPM,textvariable=DPosicion13,width=5)
DArregloPos13.grid(row=15,column=4,sticky=NSEW)
DPosicion14=StringVar()
DArregloPos14=Entry(VentanaCodificacionDCPM,textvariable=DPosicion14,width=5)
DArregloPos14.grid(row=15,column=5,sticky=NSEW)
DPosicion15=StringVar()
DArregloPos15=Entry(VentanaCodificacionDCPM,textvariable=DPosicion15,width=5)
DArregloPos15.grid(row=15,column=6,sticky=NSEW)
DPosicion16=StringVar()
DArregloPos16=Entry(VentanaCodificacionDCPM,textvariable=DPosicion16,width=5)
DArregloPos16.grid(row=15,column=7,sticky=NSEW)
DPosicion17=StringVar()
DArregloPos17=Entry(VentanaCodificacionDCPM,textvariable=DPosicion17,width=5)
DArregloPos17.grid(row=15,column=8,sticky=NSEW)
DPosicion18=StringVar()
DArregloPos18=Entry(VentanaCodificacionDCPM,textvariable=DPosicion18,width=5)
DArregloPos18.grid(row=15,column=9,sticky=NSEW)
DPosicion19=StringVar()
DArregloPos19=Entry(VentanaCodificacionDCPM,textvariable=DPosicion19,width=5)
DArregloPos19.grid(row=15,column=10,sticky=NSEW)
DPosicion20=StringVar()
DArregloPos20=Entry(VentanaCodificacionDCPM,textvariable=DPosicion20,width=5)
DArregloPos20.grid(row=15,column=11,sticky=NSEW)

#ValoresMatrizFila3
DPosicion21=StringVar()
DArregloPos21=Entry(VentanaCodificacionDCPM,textvariable=DPosicion21,width=5)
DArregloPos21.grid(row=16,column=2,sticky=NSEW)
DPosicion22=StringVar()
DArregloPos22=Entry(VentanaCodificacionDCPM,textvariable=DPosicion22,width=5)
DArregloPos22.grid(row=16,column=3,sticky=NSEW)
DPosicion23=StringVar()
DArregloPos23=Entry(VentanaCodificacionDCPM,textvariable=DPosicion23,width=5)
DArregloPos23.grid(row=16,column=4,sticky=NSEW)
DPosicion24=StringVar()
DArregloPos24=Entry(VentanaCodificacionDCPM,textvariable=DPosicion24,width=5)
DArregloPos24.grid(row=16,column=5,sticky=NSEW)
DPosicion25=StringVar()
DArregloPos25=Entry(VentanaCodificacionDCPM,textvariable=DPosicion25,width=5)
DArregloPos25.grid(row=16,column=6,sticky=NSEW)
DPosicion26=StringVar()
DArregloPos26=Entry(VentanaCodificacionDCPM,textvariable=DPosicion26,width=5)
DArregloPos26.grid(row=16,column=7,sticky=NSEW)
DPosicion27=StringVar()
DArregloPos27=Entry(VentanaCodificacionDCPM,textvariable=DPosicion27,width=5)
DArregloPos27.grid(row=16,column=8,sticky=NSEW)
DPosicion28=StringVar()
DArregloPos28=Entry(VentanaCodificacionDCPM,textvariable=DPosicion28,width=5)
DArregloPos28.grid(row=16,column=9,sticky=NSEW)
DPosicion29=StringVar()
DArregloPos29=Entry(VentanaCodificacionDCPM,textvariable=DPosicion29,width=5)
DArregloPos29.grid(row=16,column=10,sticky=NSEW)
DPosicion30=StringVar()
DArregloPos30=Entry(VentanaCodificacionDCPM,textvariable=DPosicion30,width=5)
DArregloPos30.grid(row=16,column=11,sticky=NSEW)

#ArregloMatrizFila4
DPosicion31=StringVar()
DArregloPos31=Entry(VentanaCodificacionDCPM,textvariable=DPosicion31,width=5)
DArregloPos31.grid(row=17,column=2,sticky=NSEW)
DPosicion32=StringVar()
DArregloPos32=Entry(VentanaCodificacionDCPM,textvariable=DPosicion32,width=5)
DArregloPos32.grid(row=17,column=3,sticky=NSEW)
DPosicion33=StringVar()
DArregloPos33=Entry(VentanaCodificacionDCPM,textvariable=DPosicion33,width=5)
DArregloPos33.grid(row=17,column=4,sticky=NSEW)
DPosicion34=StringVar()
DArregloPos34=Entry(VentanaCodificacionDCPM,textvariable=DPosicion34,width=5)
DArregloPos34.grid(row=17,column=5,sticky=NSEW)
DPosicion35=StringVar()
DArregloPos35=Entry(VentanaCodificacionDCPM,textvariable=DPosicion35,width=5)
DArregloPos35.grid(row=17,column=6,sticky=NSEW)
DPosicion36=StringVar()
DArregloPos36=Entry(VentanaCodificacionDCPM,textvariable=DPosicion36,width=5)
DArregloPos36.grid(row=17,column=7,sticky=NSEW)
DPosicion37=StringVar()
DArregloPos37=Entry(VentanaCodificacionDCPM,textvariable=DPosicion37,width=5)
DArregloPos37.grid(row=17,column=8,sticky=NSEW)
DPosicion38=StringVar()
DArregloPos38=Entry(VentanaCodificacionDCPM,textvariable=DPosicion38,width=5)
DArregloPos38.grid(row=17,column=9,sticky=NSEW)
DPosicion39=StringVar()
DArregloPos39=Entry(VentanaCodificacionDCPM,textvariable=DPosicion39,width=5)
DArregloPos39.grid(row=17,column=10,sticky=NSEW)
DPosicion40=StringVar()
DArregloPos40=Entry(VentanaCodificacionDCPM,textvariable=DPosicion40,width=5)
DArregloPos40.grid(row=17,column=11,sticky=NSEW)

#ArregloMatrizFila5
DPosicion41=StringVar()
DArregloPos41=Entry(VentanaCodificacionDCPM,textvariable=DPosicion41,width=5)
DArregloPos41.grid(row=18,column=2,sticky=NSEW)
DPosicion42=StringVar()
DArregloPos42=Entry(VentanaCodificacionDCPM,textvariable=DPosicion42,width=5)
DArregloPos42.grid(row=18,column=3,sticky=NSEW)
DPosicion43=StringVar()
DArregloPos43=Entry(VentanaCodificacionDCPM,textvariable=DPosicion43,width=5)
DArregloPos43.grid(row=18,column=4,sticky=NSEW)
DPosicion44=StringVar()
DArregloPos44=Entry(VentanaCodificacionDCPM,textvariable=DPosicion44,width=5)
DArregloPos44.grid(row=18,column=5,sticky=NSEW)
DPosicion45=StringVar()
DArregloPos45=Entry(VentanaCodificacionDCPM,textvariable=DPosicion45,width=5)
DArregloPos45.grid(row=18,column=6,sticky=NSEW)
DPosicion46=StringVar()
DArregloPos46=Entry(VentanaCodificacionDCPM,textvariable=DPosicion46,width=5)
DArregloPos46.grid(row=18,column=7,sticky=NSEW)
DPosicion47=StringVar()
DArregloPos47=Entry(VentanaCodificacionDCPM,textvariable=DPosicion47,width=5)
DArregloPos47.grid(row=18,column=8,sticky=NSEW)
DPosicion48=StringVar()
DArregloPos48=Entry(VentanaCodificacionDCPM,textvariable=DPosicion48,width=5)
DArregloPos48.grid(row=18,column=9,sticky=NSEW)
DPosicion49=StringVar()
DArregloPos49=Entry(VentanaCodificacionDCPM,textvariable=DPosicion49,width=5)
DArregloPos49.grid(row=18,column=10,sticky=NSEW)
DPosicion50=StringVar()
DArregloPos50=Entry(VentanaCodificacionDCPM,textvariable=DPosicion50,width=5)
DArregloPos50.grid(row=18,column=11,sticky=NSEW)

#ArregloMatrizFila6
DPosicion51=StringVar()
DArregloPos51=Entry(VentanaCodificacionDCPM,textvariable=DPosicion51,width=5)
DArregloPos51.grid(row=19,column=2,sticky=NSEW)
DPosicion52=StringVar()
DArregloPos52=Entry(VentanaCodificacionDCPM,textvariable=DPosicion52,width=5)
DArregloPos52.grid(row=19,column=3,sticky=NSEW)
DPosicion53=StringVar()
DArregloPos53=Entry(VentanaCodificacionDCPM,textvariable=DPosicion53,width=5)
DArregloPos53.grid(row=19,column=4,sticky=NSEW)
DPosicion54=StringVar()
DArregloPos54=Entry(VentanaCodificacionDCPM,textvariable=DPosicion54,width=5)
DArregloPos54.grid(row=19,column=5,sticky=NSEW)
DPosicion55=StringVar()
DArregloPos55=Entry(VentanaCodificacionDCPM,textvariable=DPosicion55,width=5)
DArregloPos55.grid(row=19,column=6,sticky=NSEW)
DPosicion56=StringVar()
DArregloPos56=Entry(VentanaCodificacionDCPM,textvariable=DPosicion56,width=5)
DArregloPos56.grid(row=19,column=7,sticky=NSEW)
DPosicion57=StringVar()
DArregloPos57=Entry(VentanaCodificacionDCPM,textvariable=DPosicion57,width=5)
DArregloPos57.grid(row=19,column=8,sticky=NSEW)
DPosicion58=StringVar()
DArregloPos58=Entry(VentanaCodificacionDCPM,textvariable=DPosicion58,width=5)
DArregloPos58.grid(row=19,column=9,sticky=NSEW)
DPosicion59=StringVar()
DArregloPos59=Entry(VentanaCodificacionDCPM,textvariable=DPosicion59,width=5)
DArregloPos59.grid(row=19,column=10,sticky=NSEW)
DPosicion60=StringVar()
DArregloPos60=Entry(VentanaCodificacionDCPM,textvariable=DPosicion60,width=5)
DArregloPos60.grid(row=19,column=11,sticky=NSEW)

#MatrizArregloFila7
DPosicion61=StringVar()
DArregloPos61=Entry(VentanaCodificacionDCPM,textvariable=DPosicion61,width=5)
DArregloPos61.grid(row=20,column=2,sticky=NSEW)
DPosicion62=StringVar()
DArregloPos62=Entry(VentanaCodificacionDCPM,textvariable=DPosicion62,width=5)
DArregloPos62.grid(row=20,column=3,sticky=NSEW)
DPosicion63=StringVar()
DArregloPos63=Entry(VentanaCodificacionDCPM,textvariable=DPosicion63,width=5)
DArregloPos63.grid(row=20,column=4,sticky=NSEW)
DPosicion64=StringVar()
DArregloPos64=Entry(VentanaCodificacionDCPM,textvariable=DPosicion64,width=5)
DArregloPos64.grid(row=20,column=5,sticky=NSEW)
DPosicion65=StringVar()
DArregloPos65=Entry(VentanaCodificacionDCPM,textvariable=DPosicion65,width=5)
DArregloPos65.grid(row=20,column=6,sticky=NSEW)
DPosicion66=StringVar()
DArregloPos66=Entry(VentanaCodificacionDCPM,textvariable=DPosicion66,width=5)
DArregloPos66.grid(row=20,column=7,sticky=NSEW)
DPosicion67=StringVar()
DArregloPos67=Entry(VentanaCodificacionDCPM,textvariable=DPosicion67,width=5)
DArregloPos67.grid(row=20,column=8,sticky=NSEW)
DPosicion68=StringVar()
DArregloPos68=Entry(VentanaCodificacionDCPM,textvariable=DPosicion68,width=5)
DArregloPos68.grid(row=20,column=9,sticky=NSEW)
DPosicion69=StringVar()
DArregloPos69=Entry(VentanaCodificacionDCPM,textvariable=DPosicion69,width=5)
DArregloPos69.grid(row=20,column=10,sticky=NSEW)
DPosicion70=StringVar()
DArregloPos70=Entry(VentanaCodificacionDCPM,textvariable=DPosicion70,width=5)
DArregloPos70.grid(row=20,column=11,sticky=NSEW)

#ArregloMatrizFila8
DPosicion71=StringVar()
DArregloPos71=Entry(VentanaCodificacionDCPM,textvariable=DPosicion71,width=5)
DArregloPos71.grid(row=21,column=2,sticky=NSEW)
DPosicion72=StringVar()
DArregloPos72=Entry(VentanaCodificacionDCPM,textvariable=DPosicion72,width=5)
DArregloPos72.grid(row=21,column=3,sticky=NSEW)
DPosicion73=StringVar()
DArregloPos73=Entry(VentanaCodificacionDCPM,textvariable=DPosicion73,width=5)
DArregloPos73.grid(row=21,column=4,sticky=NSEW)
DPosicion74=StringVar()
DArregloPos74=Entry(VentanaCodificacionDCPM,textvariable=DPosicion74,width=5)
DArregloPos74.grid(row=21,column=5,sticky=NSEW)
DPosicion75=StringVar()
DArregloPos75=Entry(VentanaCodificacionDCPM,textvariable=DPosicion75,width=5)
DArregloPos75.grid(row=21,column=6,sticky=NSEW)
DPosicion76=StringVar()
DArregloPos76=Entry(VentanaCodificacionDCPM,textvariable=DPosicion76,width=5)
DArregloPos76.grid(row=21,column=7,sticky=NSEW)
DPosicion77=StringVar()
DArregloPos77=Entry(VentanaCodificacionDCPM,textvariable=DPosicion77,width=5)
DArregloPos77.grid(row=21,column=8,sticky=NSEW)
DPosicion78=StringVar()
DArregloPos78=Entry(VentanaCodificacionDCPM,textvariable=DPosicion78,width=5)
DArregloPos78.grid(row=21,column=9,sticky=NSEW)
DPosicion79=StringVar()
DArregloPos79=Entry(VentanaCodificacionDCPM,textvariable=DPosicion79,width=5)
DArregloPos79.grid(row=21,column=10,sticky=NSEW)
DPosicion80=StringVar()
DArregloPos80=Entry(VentanaCodificacionDCPM,textvariable=DPosicion80,width=5)
DArregloPos80.grid(row=21,column=11,sticky=NSEW)

#ArregloMatrizFila9
DPosicion81=StringVar()
DArregloPos81=Entry(VentanaCodificacionDCPM,textvariable=DPosicion81,width=5)
DArregloPos81.grid(row=22,column=2,sticky=NSEW)
DPosicion82=StringVar()
DArregloPos82=Entry(VentanaCodificacionDCPM,textvariable=DPosicion82,width=5)
DArregloPos82.grid(row=22,column=3,sticky=NSEW)
DPosicion83=StringVar()
DArregloPos83=Entry(VentanaCodificacionDCPM,textvariable=DPosicion83,width=5)
DArregloPos83.grid(row=22,column=4,sticky=NSEW)
DPosicion84=StringVar()
DArregloPos84=Entry(VentanaCodificacionDCPM,textvariable=DPosicion84,width=5)
DArregloPos84.grid(row=22,column=5,sticky=NSEW)
DPosicion85=StringVar()
DArregloPos85=Entry(VentanaCodificacionDCPM,textvariable=DPosicion85,width=5)
DArregloPos85.grid(row=22,column=6,sticky=NSEW)
DPosicion86=StringVar()
DArregloPos86=Entry(VentanaCodificacionDCPM,textvariable=DPosicion86,width=5)
DArregloPos86.grid(row=22,column=7,sticky=NSEW)
DPosicion87=StringVar()
DArregloPos87=Entry(VentanaCodificacionDCPM,textvariable=DPosicion87,width=5)
DArregloPos87.grid(row=22,column=8,sticky=NSEW)
DPosicion88=StringVar()
DArregloPos88=Entry(VentanaCodificacionDCPM,textvariable=DPosicion88,width=5)
DArregloPos88.grid(row=22,column=9,sticky=NSEW)
DPosicion89=StringVar()
DArregloPos89=Entry(VentanaCodificacionDCPM,textvariable=DPosicion89,width=5)
DArregloPos89.grid(row=22,column=10,sticky=NSEW)
DPosicion90=StringVar()
DArregloPos90=Entry(VentanaCodificacionDCPM,textvariable=DPosicion90,width=5)
DArregloPos90.grid(row=22,column=11,sticky=NSEW)

#ArregloMatrizFila10
DPosicion91=StringVar()
DArregloPos91=Entry(VentanaCodificacionDCPM,textvariable=DPosicion91,width=5)
DArregloPos91.grid(row=23,column=2,sticky=NSEW)
DPosicion92=StringVar()
DArregloPos92=Entry(VentanaCodificacionDCPM,textvariable=DPosicion92,width=5)
DArregloPos92.grid(row=23,column=3,sticky=NSEW)
DPosicion93=StringVar()
DArregloPos93=Entry(VentanaCodificacionDCPM,textvariable=DPosicion93,width=5)
DArregloPos93.grid(row=23,column=4,sticky=NSEW)
DPosicion94=StringVar()
DArregloPos94=Entry(VentanaCodificacionDCPM,textvariable=DPosicion94,width=5)
DArregloPos94.grid(row=23,column=5,sticky=NSEW)
DPosicion95=StringVar()
DArregloPos95=Entry(VentanaCodificacionDCPM,textvariable=DPosicion95,width=5)
DArregloPos95.grid(row=23,column=6,sticky=NSEW)
DPosicion96=StringVar()
DArregloPos96=Entry(VentanaCodificacionDCPM,textvariable=DPosicion96,width=5) 
DArregloPos96.grid(row=23,column=7,sticky=NSEW)
DPosicion97=StringVar()
DArregloPos97=Entry(VentanaCodificacionDCPM,textvariable=DPosicion97,width=5)
DArregloPos97.grid(row=23,column=8,sticky=NSEW)
DPosicion98=StringVar()
DArregloPos98=Entry(VentanaCodificacionDCPM,textvariable=DPosicion98,width=5)
DArregloPos98.grid(row=23,column=9,sticky=NSEW)
DPosicion99=StringVar()
DArregloPos99=Entry(VentanaCodificacionDCPM,textvariable=DPosicion99,width=5)
DArregloPos99.grid(row=23,column=10,sticky=NSEW)
DPosicion100=StringVar()
DArregloPos100=Entry(VentanaCodificacionDCPM,textvariable=DPosicion100,width=5)
DArregloPos100.grid(row=23,column=11,sticky=NSEW)

ValorMinimoRandom=StringVar()
EntryMinimoVal=Entry(VentanaCodificacionDCPM, textvariable=ValorMinimoRandom)
EntryMinimoVal.grid(row=4, column=0)
Espacio2=Label(VentanaCodificacionDCPM,text="ingrese el valor maximo de los valores que desea")
Espacio2.grid(row=5,column=0)
ValorMaximoRandom=StringVar()
EntryMaximoVal=Entry(VentanaCodificacionDCPM, textvariable=ValorMaximoRandom)
EntryMaximoVal.grid(row=6,column=0)

LabelMostrarNumeroBits=Label(VentanaCodificacionDCPM, text=" ")
LabelMostrarNumeroBits.grid(row=10, column=0)

BotonCalculo=Button(VentanaCodificacionDCPM, text="Calculo Por Filas", command=lambda : AgruparLecturaFilas(CreacionMatrices()))
BotonCalculo.grid(row=7, column=0)
BotonCalculo2=Button(VentanaCodificacionDCPM, text="Calculo Por Columnas", command=lambda : AgruparLecturaColumnas(CreacionMatrices()))
BotonCalculo2.grid(row=8, column=0)
BotonCalculo3=Button(VentanaCodificacionDCPM, text="Calculo Por Zig Zag", command=lambda : AgruparLecturaZigZag(CreacionMatrices()))
BotonCalculo3.grid(row=9,column=0)
EntryTecnica=Entry(VentanaCodificacionDCPM)

LabelMostrarTramaTotal=Label(VentanaCodificacionDCPM, text=" ")
LabelMostrarTramaTotal.grid(row=13, column=0)

LabelError=Label(VentanaCodificacionDCPM, text=" ")
LabelError.grid(row=20, column=0)

VentanaCodificacionDCPM.mainloop()